In [3]:
import numpy as np

# 创建数据

In [22]:
# 创建numpy数组
a = np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9]])

# 按顺序创建numpy数据，rehape可以改变数组形状和维度
b = np.arange(1, 11).reshape(2, 5)

print(f'a = {a}')
print(f'b = {b}')

a = [[1 2 3 4 5]
 [5 6 7 8 9]]
b = [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
# array.ndim可以输出数组的维度
print(a.ndim)

2


# 添加数据

In [24]:
# 可以使用np.concatenate()在任意轴上加上数据
print(np.concatenate([a, b], axis = 0))  # axis=0代表加在行后面
print(np.concatenate([a, b], axis = 1))  # axis=0代表加在列右边

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 5  6  7  8  9  6  7  8  9 10]]


# 合并数据

In [26]:
# 可以使用np.concatenate()在任意轴上合并数据
print(np.concatenate([a, b], axis = 0))  # axis=0代表加在行后面
print(np.concatenate([a, b], axis = 1))  # axis=0代表加在列右边

# 也可以使用np.vstack()和np.hstack()
print(np.vstack([a, b])) # 水平合并
print(np.hstack([a, b])) # 列合并

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 5  6  7  8  9  6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  1  2  3  4  5]
 [ 5  6  7  8  9  6  7  8  9 10]]


# 形态

In [28]:
# 使用np.array.shape
print(a.shape)

# np.array.shape[0] 可以知道有多少行
print(a.shape[0])

# np.array.shape[1] 可以知道有多少列
print(a.shape[1])

# np.array.size是知道array里面有多少数据
print(a.size)

(2, 5)
2
5
10
